openapi: 3.0.1
info:
  title: EnviroNZ-API
  description: "Welcome to the `EnviroNZ-API`. This API can be used for accessing data directly from our databases. <br>Please note you must have an API key to use any of the API calls. Without an API key, it will not work."
  version: "0.1.0"
servers:
  - url: https://environz-api.azurewebsites.net/api
paths:
  # "/TCC/UpdateCustomer/{id}":
  #   post:
  #     summary: UpdateCustomer
  #     operationId: post-updatecustomer
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: "integer"
  #     responses:
  #       "200":
  #         description: ""
  /Status:
    get:
      summary: Get the EnviroNZ-API status
      operationId: get-status
      description: >
        This simple API call is used to check if the API is online and working.
        If there are any API issues, they will be listed here.
      tags:
        - Status
      responses:
        "200":
          description: ""
  # /FuncGetStatusCodes:
  #   get:
  #     summary: FuncGetStatusCodes
  #     operationId: get-funcgetstatuscodes
  #     responses:
  #       "200":
  #         description: ""
  "/TCC/GetCustomer/{id}":
    get:
      summary: Get one customer record by their customer code (id)
      operationId: get-getcustomer
      tags:
        - TCC - Customers
      parameters:
        - name: id
          description: TCC Customer Code
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: ""
  # /TCC/GetCustomers:
  #   get:
  #     summary: GetCustomers
  #     operationId: get-getcustomers
  #     responses:
  #       "200":
  #         description: ""
  "/TCC/GetAllCustomerAddresses/{id}":
    get:
      summary: Get all addresses for one customer by their customer code (id)
      operationId: get-getallcustomeraddresses
      tags:
        - TCC - Customers
      parameters:
        - name: id
          description: TCC Customer Code
          in: path
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: ""
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-functions-key
      in: header
security:
  - apiKeyHeader: []
