openapi: 3.0.1
info:
  title: EnviroNZ-API
  description: EnviroNZ API for Western Bay of Plenty
  version: "1.0"
servers:
  - url: https://environz-api-dev.azurewebsites.net/api
  - url: http://localhost:7071/api
paths:
  /Status:
    get:
      summary: Status
      operationId: get-status
      tags:
        - Status
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicerequesttypes:
    get:
      summary: Returns the list of service request types
      operationId: get-servicerequesttypes
      tags:
        - Service Request
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicetypes:
    get:
      summary: Returns the list of service types
      operationId: get-servicetypes
      tags:
        - Service Request
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicerequest/{id}:
    get:
      summary: Returns a specific service request
      operationId: get-servicerequestid
      tags:
        - Service Request
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicerequest:
    get:
      summary: Returns the full list of service types
      operationId: get-allservicerequests
      tags:
        - Service Request
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
    post:
      tags:
        - Service Request
      summary: Send service request data
      operationId: post-servicerequest
      requestBody:
        description: WBOP service request data for EnviroWaste
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceRequest"
        required: true
      responses:
        "200":
          description: "Success"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized Error"
        "404":
          description: "Not Found Error"
        "500":
          description: "Internal Server Error"
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-functions-key
      in: header
  schemas:
    ServiceRequest:
      type: object
      properties:
        CustomerCode:
          type: number
          format: integer
        WBOPReference:
          type: string
        ServiceRequestType:
          type: string
        ServiceType:
          type: string
        Comments:
          type: string
        Attachment:
          type: string
security:
  - apiKeyHeader: []
