openapi: 3.0.1
info:
  title: EnviroNZ-API
  description: EnviroNZ API for Western Bay of Plenty
  version: "1.0"
servers:
  - url: https://environz-api-dev.azurewebsites.net/api
  - url: https://environz-api.azurewebsites.net/api
paths:
  /Status:
    get:
      summary: Status
      operationId: get-status
      tags:
        - Status
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicerequesttypes:
    get:
      summary: Returns the list of service request types
      operationId: get-servicerequesttypes
      tags:
        - Service Request
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicetypes:
    get:
      summary: Returns the list of service types
      operationId: get-servicetypes
      tags:
        - Service Request
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
  /wbop/servicerequest:
    get:
      summary: Returns the list of service types based on filters. Leave filters blank to return all records
      operationId: get-allservicerequests
      tags:
        - Service Request
      parameters:
        - name: customerCode
          in: query
          required: false
          schema:
            type: number
        - name: wbopReference
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "Success"
        "401":
          description: "Unauthorised"
        "404":
          description: "Not Found"
    post:
      tags:
        - Service Request
      summary: Send service request data
      operationId: post-servicerequest
      requestBody:
        description: WBOP service request data for EnviroWaste
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateServiceRequest"
        required: true
      responses:
        "200":
          description: "Success"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized Error"
        "404":
          description: "Not Found Error"
        "500":
          description: "Internal Server Error"
    put:
      tags:
        - Service Request
      summary: "Update an existing service request"
      description: "Add additional comments to an already submitted service request"
      operationId: "put-servicerequest"
      parameters:
        - in: "query"
          name: "wbopReference"
          description: "WBOP Reference Code to be updated"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateServiceRequest"
        required: true
      responses:
        "200":
          description: "Success"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized Error"
        "404":
          description: "Not Found Error"
        "500":
          description: "Internal Server Error"
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-functions-key
      in: header
  schemas:
    CreateServiceRequest:
      type: object
      properties:
        CustomerCode:
          type: number
          format: integer
        WBOPReference:
          type: string
        ServiceRequestType:
          type: string
        ServiceType:
          type: string
        Comments:
          type: string
        Attachment:
          type: string
    UpdateServiceRequest:
      type: object
      properties:
        Comments:
          type: string
security:
  - apiKeyHeader: []
